spring.datasource.url=jdbc:postgresql://localhost:5432/order_management_api
spring.datasource.username=postgres
spring.datasource.password=100520
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true