spring.datasource.url=jdbc:postgresql://railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=WaoYTaklktKyyrlpKxzljjWfCZHhWjXW
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true