spring.datasource.url=jdbc:postgresql://postgres:ATuMaIxccgkqDvwrmiKtNjtOmQAcfpXb@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=ATuMaIxccgkqDvwrmiKtNjtOmQAcfpXb
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true